### ISSUE TITLE
Visualize data

### ISSUE THREAD

**Issue by ghost** [marvinroger/Dofus-Tools#2]
Hi !
First of all, great work, I'm trying to understand how it works !

I'm having trouble to visualize the data (for example as png)
I looked at this closed issue : https://github.com/marvinroger/Dofus-Tools/issues/1#issuecomment-122389237

But I get the following issue : 
`Traceback (most recent call last):
  File "maps.py", line 23, in <module>
    image = Image.open(buff)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2861, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f4fea9efa90>`

Do you have any idea ?

**Comment by marvinroger** [comment]
Hi, thanks a lot, and sorry for the delay!

This is a really old project that is not supported anymore. Therefore, I am unable to provide support.

Good luck!
